Noticias/Noticias/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppNoticias.url')),
]

Noticias/AppNoticias/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    titulo = models.CharField(max_length=100)
    categoria_imagen = models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categorias'

    def __str__(self):
        return self.titulo

class Noticia(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    detalles = models.TextField(max_length=20000)
    imagen = models.ImageField(upload_to='imgs/')
    add_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='Noticias'
    def __str__(self):
        return self.titulo

class Comentario(models.Model):
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    comentario = models.TextField(max_length=500)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural='Comentarios'
    def __str__(self):
        return self.comentario

Noticias/AppNoticias/views.py
from django.shortcuts import render
from .models import Noticia, Categoria, Comentario
from django.contrib import messages
# Create your views here.

def home(request):
    primer_noticia=Noticia.objects.first()
    tres_noticia=Noticia.objects.all()[1:3]
    tres_categoria=Categoria.objects.all()[0:3]

    return render (request, 'home.html', {
        'primer_noticia': primer_noticia,
        'tres_noticia': tres_noticia,
        'tres_categoria': tres_categoria
    })

def categoria(request,):
    categorias=Categoria.objects.all()

    return render (request, 'categorias.html',{
        'categorias': categorias
    })

def toda_categoria(request, id):

    categorias=Categoria.objects.get(id=id)
    noticia = Noticia.objects.filter(categoria=categorias)

    return render (request, 'toda_categoria.html',{
        'todas_noticias': noticia,
        'categoria': categorias

    })

def todas_noticias(request):
    todas_noticias=Noticia.objects.all()

    return render (request, 'todas_noticias.html', {
        'todas_noticias': todas_noticias
    })

def detalles(request, id):

    noticia=Noticia.objects.get(pk=id)
    if request.method == 'POST':
        nombre = request.POST['nombre']
        comentario = request.POST['mensaje']
        Comentario.objects.create(
            noticia=noticia,
            nombre=nombre,

            comentario=comentario
        )
    messages.success(request,'Comentario enviado a moderacion')
    comentario = Comentario.objects.filter(noticia=noticia, status=True).order_by('-id')
    categoria=Categoria.objects.get(id=noticia.categoria.id)
    noticia_relacionada=Noticia.objects.filter(categoria=categoria).exclude(id=id)

    return render (request, 'detalles.html', {
        'noticia': noticia,
        'noticia_relacionada': noticia_relacionada,
        'comentario': comentario
    })

Noticias/AppNoticias/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Pagina inicio{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">Noticias Delicias</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item {% if request.path == '/' %} active {% endif %}"   >
		        <a class="nav-link" href="/">Inicio</a>
			 </li>
		      <li class="nav-item {% if request.path == '/todas_noticias' %} active {% endif %}">
		        <a class="nav-link" href="{% url 'todas_noticias' %}">Todas las noticias</a>
		      </li>
				 <li class="nav-item {% if request.path == '/categorias' %} active {% endif %}">
		        <a class="nav-link" href="{% url 'categorias' %}">Todas las ciudades</a>
		      </li>

		    </ul>
		  </div>
	  	</div>
    </nav>

    {% block content %}
    {% endblock %}

<hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Volver arriba</a>
    </p>
    <p>Nos reservamos el derecho a ser demandados</p>
  </div>
</footer>
</body>
</html>

Noticias/AppNoticias/templates/categorias.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Todas las categorias</h3>
    <div class="row">
		<!-- Category Box -->
		{% for categoria in categorias %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img height="250" width="100" src="/media/{{categoria.categoria_imagen}}" class="card-img-top" alt="{{categoria.titulo}}">
			  <div class="card-body">
			    <h5 class="card-title">{{categoria.titulo}}</h5>
			    <hr/>
			    <p class="card-text"><a href="categoria/{{categoria.id}}" class="btn btn-sm btn-primary">Todas las noticias</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

Noticias/AppNoticias/templates/detalles.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
			  <div class="card-body">
			    <h5 class="card-title">{{noticia.titulo}}</h5>
			    <hr/>
			    <p class="card-text">{{noticia.detalles}}</p>
			  </div>
			  <div class="card-footer">
			  	En <a href="/categoria/{{noticia.categoria.id}}">{{noticia.categoria.titulo}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Añadir comentario</h6>
				<div class="card-body">
					{% for mensaje in mensajes %}
					<p class="text-success">{{mensaje}}</p>
					{% endfor %}
					<form method="post" action="/detalles/{{noticia.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Nombre<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="nombre" required class="form-control" />
							</div>
						</div>
                        <div class="form-group row">

							<div class="col-md-10">

							</div>

						</div>
						<div class="form-group row">
							<label class="col-md-2">comentario<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="mensaje" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comentarios</h6>
				<div class="card-body">
					{% for comentario in comentario %}
					<blockquote class="blockquote text-left">
					  <p class="mb-0">{{comentario.comentario}}</p>
					  <footer class="blockquote-footer">{{comentario.nombre}}</footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">En esta ciudad</h3>
			<!-- Category Box -->
			{% for noticia in noticia_relacionada %}
			<div class="card mb-3 shadow">
                <img src="/media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
			  <div class="card-body">
			    <h5 class="card-title">{{noticia.titulo}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detalles/{{noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

Noticias/AppNoticias/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{primer_noticia.imagen}}" class="card-img-top" alt="{{primer_noticia.titulo}}">
			  <div class="card-body">
			    <h5 class="card-title">{{primer_noticia.titulo}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detalles/{{primer_noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for noticia in tres_noticia %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img height="120" width="80" src="media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{noticia.titulo}}</h5>
			        <p class="card-text"><a href="/detalles/{{noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for categoria in tres_categoria %}
	<h3 class="border-bottom pb-1">{{categoria.titulo}} <a href="/categoria/{{categoria.id}}" class="float-right btn btn-sm btn-dark">En esta ciudad</a></h3>
	<div class="row my-4">
		{% for noticia in categoria.noticia_set.all %}
			{% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img height="120" width="60" src="/media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
				<div class="card-body">
					<h5 class="card-title">{{noticia.titulo}}</h5>
					<hr/>
					<p class="card-text"><a href="/detalles/{{noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
				</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!-- End Single Category -->
</main>
{% endblock %}

Noticias/AppNoticias/templates/toda_categoria.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Todas las noticias de {{categoria.titulo}}</h3>
    <!-- News Box -->
    {% for noticia in todas_noticias %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{noticia.titulo}}</h5>
	        <p class="card-text">{{noticia.detalles}}</p>
	        <p class="card-text"><a href="/detalles/{{noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

Noticias/AppNoticias/templates/todas_noticias.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Todas las noticias</h3>
    <!-- News Box -->
    {% for noticia in todas_noticias %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img  height="150" width="80" src="/media/{{noticia.imagen}}" class="card-img-top" alt="{{noticia.titulo}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{noticia.titulo}}</h5>
	        <p class="card-text">{{noticia.detalles}}</p>
	        <p class="card-text"><a href="/detalles/{{noticia.id}}" class="btn btn-sm btn-primary">Leer más</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}